services:
  go-shorturl-postgresql:
    image: postgres:15
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped

  go-shorturl-minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z-cpuv1
    container_name: ${MINIO_CONTAINER_NAME}
    ports:
      - '${MINIO_PORT_SERVICE}:9000' # API Port
      - '${MINIO_PORT_UI}:9001' # Web UI Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: weare12we
      MINIO_DEFAULT_BUCKETS: object-storage-bucket
      MINIO_VOLUMES: /data
    command: server --console-address ":9001" /data # รัน MinIO โดยเปิด Web UI บน 9001
    networks:
      - app-net
    volumes:
      - minio_data:/data

  e-wallet-api:
    build:
      context: ./
    env_file:
      - .env
    container_name: ${E_WALLET_API_CONTAINER}
    ports:
      - '${PORT}:${PORT}'
    networks:
      - app-net
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - e-wallet-mysql
      - e-wallet-minio

networks:
  app-net:
    name: ${CONTAINER_NETWORK}
    external: true

volumes:
  dbdata:
    name: ${MYSQL_DATABASE_CONTAINER}
  minio_data:
    name: ${MINIO_CONTAINER}
